# The URL the site will be built for
base_url = "https://backendsouls.dev"

compile_sass = false

minify_html = true

generate_feed = true

default_language = "en"

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "anemone"

taxonomies = [
    {name = "tags", feed = true},
]

[markdown]
render_emoji = true
external_links_target_blank = true
smart_punctuation = true
highlight_code = true
highlight_theme = "gruvbox-dark"

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[link_checker]
internal_level = "warn"

[extra]
author = "Emanuel D R Sena"
display_author = true
favicon = "favicon.ico"
image = ""
default_theme = "dark"
list_pages = false
twitter_card = false
toc = true

[[extra.header_nav]]
en = { name = "Home -- ", url = "/" }

[[extra.header_nav]]
en = { name = "Journal -- ", url = "/journal" }

[[extra.header_nav]]
en = { name = "About -- ", url = "/about" }

[[extra.header_nav]]
en = { name = "[Blog]", url = "/blog" }

